### ISSUE TITLE
Adding a line when first m_ID is not 0

### ISSUE THREAD

**Issue by Kelzano** [WowDevTools/WDBXEditor#22]
I noticed something very disturbing, whenever the first line's m_ID is not 0, it will automatically add a line with m_ID 0, causing the m_ID 1 to become the 0, the 2 becoming the 1 and so on, leading to a huge mess, what can I do to fix this ?

**Comment by barncastle** [comment]
I'm not sure how to replicate this, could you let me know:
* If there is a specific file that this happens on (expansion and name)?
* The process you're doing that makes this occur - is it just opening a file or are you adding a new line etc

**Comment by Aszune** [comment]
I have the same problem and it's a big problem for me.

I use WDBX Editor **1.1.0** and I have the latest TC **7.2.5 24742**
I need insert thousand of lines in the GameObjectDisplayInfo.db2 because I'm trying to make a gameobject custom patch for 7.2.5

I have all data in a **.csv** file, but when I import the data and save the db2, when I reopen the db2, I see the first **m_ID** with a **0** ID, and this makes all data inusable because the IDs not correspond with the properly data in gameobject_template

The first m_ID should always be number 1

I don't know why this happens, but it ruins the entire ID order in the db2

Sorry for my bad english.

**Comment by barncastle** [comment]
@Aszune That's perfect, thank you!

I've just released a new build that fixes this issue - I've tested with the examples provided.
If the issue persists obviously let me know.

(FYI, records 61586 and 61587 are duplicates in your CSV file.)

**Comment by Aszune** [comment]
Thanks, now works perfect!!
And thanks for notice me the duplicate lines, my custom patch it's done :3
