### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by BBCnewstoday** [WowDevTools/WDBXEditor#23]
Well, I can't get the reason of bug, but each time I editing Spell.dbc (1.12.1 version), its become corrupted (all DoTs timers are broken). I think there's some issue with m_effectAmplitude decrypt method.
Sorry, really can show you more info, except of where the problem is.
P.S. for rend effectamplitude should be 3000, but in WDBX its shows 4,203895E-42 , and when importing to SQL it become 4... And when patching SQL>DBC its become 0.

btw would be nice if someone can check other possible broken rows with same issue(it bet its possible)

**Comment by barncastle** [comment]
Looks like that column should be an integer instead of a float.
I have updated the 1.12.1 definitions which you can download from [here](https://github.com/WowDevTools/WDBXEditor/blob/dev/WDBXEditor/Definitions/Classic%201.12.1%20(5875).xml). Just drop that over the top of the current definition in the "Definitions" folder.
