### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by lvzhijie** [WowDevTools/WDBXEditor#24]
where can i found AdvanceDataGridView.dll?
Second, c# has no 'long'

**Comment by barncastle** [comment]
It sounds like you don't have a C# 7 compatible version of Visual Studio. Can you get the latest version of Visual Studio 2017 and try with that? 

AdvanceDataGridView.dll is a project included in this solution however it's probably not compiling due to the other issue.

If this doesn't work, let me know and reopen this issue.

**Comment by lvzhijie** [comment]
Thank you, i still use visual studio 2015.
I had upgrated this.
