### ISSUE TITLE
Copy rows does not set db2 to modified

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/WDBXEditor#58]
Hello, heres the issue: 

When I copy a row in the item.db2 from current legion patch and insert it into a new row. Without changing any data WDBX does not recognize any changes and therefor not saves the new entry. After reload its gone. Theres also no * after the File indicating any changes.

https://gyazo.com/91d1719e3067efdd739491b7721d64b7

Steops to reproduce:

1. Open item.db2
2. Copy any row
3. insert row in complete new Row.
4. Save
5. Reopen
6. Entry gone.

This can be prevented by changing any colum entry to a diffrent value. Still  a huge bug though.

**Comment by barncastle** [comment]
I'm struggling to replicate this. Does the row count in the 'Stats' panel change when you insert the new row? Is it the same row count amount when you reload?

Also, try searching specifically for that ID, if you're looking for the same position in the gridview it might not be there due to how I've implemented copy rows. E.g. I copy row 25, insert it into 158000, its at the bottom then when I reload its below row 25. (I can change this so it orders by ID for copy rows, is that worth doing?)

The change indicator is missing, good catch - I'll fix that!

**Comment by Kallar12** [comment]
Ahm. Yeah those got reordered. Could you make a setting to not reorder this? I would prefer my records to be at the end of the file not somewhere inbetween.

**Comment by barncastle** [comment]
Brilliant! Latest update as of ~42 minutes ago changes this.
