### ISSUE TITLE
Invalid ID. Out of range.

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/WDBXEditor#60]
Hello I was trying to insert a line at a id (2500153) in 7.3.5 textureFileData. 
A error pops up saying that its out of the range of the column. This column is a uint32 and should easily fit 2500153.

**Comment by barncastle** [comment]
WDCx contains column bitwidth limits that WDBX enforces. This means that the supported type vs the definition type doesn't always match - for instance this value is actually a uint22. See #56 and #51.

Whether or not these limits can be removed is something that I've not investigated yet. So, for the meantime, it is what it is.

**Comment by barncastle** [comment]
I've just updated the dev ranch so that on save, it removes the bit limits (and by association increases the RecordSize). I've not really tested this so would appreciate if you could let me know if 1. the client explodes and 2. if it resolves the issue.

@MrXJKz and @Leschen - you might want to jump in on this.

**Comment by barncastle** [comment]
I've had a few people test this and it appears to work correctly.
Limits now definition driven and correlate to the client's in-memory representation.
