### ISSUE TITLE
Will this tool work on the latest builds?

### ISSUE THREAD

**Issue by bryansray** [WowDevTools/WDBXEditor#7]
I seem to be getting "No Records Found" errors when running this against the latest. Just wanted to check if I'm doing something wrong.

I'm running this against the `QuestCache.wdb` file.

**Comment by barncastle** [comment]
Have you updated the definition for Legion QuestCache?

The WDB files themselves appear to be the same structure so I'm fairly sure it is just the definition. As there isn't much interest in the WDB files I've only (lazily) been including the working structures I've found online.

The structures usually mirror the SMSG_QUERY_%_RESPONSE packets +/- a few columns so QuestCache should be near enough the below structure for 7.2.0:
https://github.com/TrinityCore/TrinityCore/blob/86b98686a95e23247ecb774fb23ecd5b8d94b97b/src/server/game/Server/Packets/QuestPackets.cpp#L56 

I'll have a look when I get the chance

**Comment by bryansray** [comment]
> Have you updated the definition for Legion QuestCache?

Unfortunately, I'm new to this whole domain. I don't suppose you could provide me an example of what this means? How do I update the definition for Legion QuestCache? Where is the definition stored?

Perhaps I could get some advice from you as well. My goal is to data mine `Quest` and `Item` information from the game. I assumed that the easiest place to get this data from, would be the WDB cached files? However, it seems that based on your response, that might not be the case?

Is there a better place that I could mine Quest and/or Item data?

**Comment by barncastle** [comment]
Apologies there's a lot jargon in my last response. WDBX uses XML definitions to tell it what the column structure is for the files; this is mainly due to frequent changes and also the inaccuracies of guessing columns types. The problem I think you'll face with the WDB files is doing every quest and obtaining every item to populate the files, that being said, I'll have a look but it might take some time to figure out the file structure.

Personally, I'd look at https://github.com/TrinityCore. They're working on a Legion emulator so have the most complete dataset (MySQL) which is being maintained by a large community. It will also allow you to do joins on additional data like quest chains, givers etc. There is also a bunch of data mining tools they've released the source for.

Wowhead also provides data in XML format, you just need to suffix "&xml" to the end of any item or spell url i.e. http://www.wowhead.com/item=128476&xml. For quests you'll need to scrape by the looks of it.

Blizzard has their own api which looks like you're already using. This obviously has limited quest information but you could pull down all the ids to use in Wowhead.

I'd also ask about on http://www.model-changing.net/ and http://www.modcraft.io - they're geared towards modding but they're pretty helpful people and know their stuff.

Using a combination of all the above should get you very close to a complete dataset I think.
